### ISSUE TITLE
Getting Cannot access package artifact

### ISSUE THREAD

**Issue by qngdt** [juanjoDiaz/serverless-plugin-warmup#309]
My project is using [serverless-package-python-functions](https://github.com/ubaniabalogun/serverless-package-python-functions) for packaging Python functions. I'm getting this error when trying to package my functions with warmup plugin

```
Error:
Cannot access package artifact at "_build/{serviceName}-{stage}-warmup-plugin-default.zip" (for "warmUpPluginDefault"): ENOENT: no such file or directory, access '{serviceName}-{stage}-warmup-plugin-default.zip'
```
Here is my warmup config in the custom stage
```
warmup:
    default:
      enabled: false
      cleanFolder: false
      package:
        individually: True
        artifact: ${self:custom.pkgPyFuncs.buildDir}/{serviceName}-${opt:stage}-warmup-plugin-default.zip
``` 
And the config at the function I want to warmup
```
  warmup:
    default:
      enabled: true
```
From my knowledge it's looking for the zip file containing the content of `.warmup` folder. So I tried to add the `artifact` part in my warmup config, but the error still hasn't been resolved. Would love someone could help me on this

**Comment by juanjoDiaz** [comment]
You shouldn't really be using artifact since you are not providing your own zip.
Also indentation seems off.

This should do:
```yaml
warmup:
    default:
        enabled: false
        cleanFolder: false
```

**Comment by qngdt** [comment]
> You shouldn't really be using artifact since you are not providing your own zip. Also indentation seems off.
> 
> This should do:
> 
> ```yaml
> warmup:
>     default:
>         enabled: false
>         cleanFolder: false
> ```

Hi, thanks for your input but the error still persist. I've created an example repo with the error output [here](https://github.com/qngdt/serverless-python-package-warmup)
My guess would be because of the [serverless-package-python-functions](https://github.com/ubaniabalogun/serverless-package-python-functions) was tampering with the packaging stage.

**Comment by juanjoDiaz** [comment]
Hi, sorry for the delay answering.

Did you figure this one out?
Can you set up a sample repo so I can reproduce?

**Comment by qngdt** [comment]
> Hi, sorry for the delay answering.
> 
> Did you figure this one out? Can you set up a sample repo so I can reproduce?

Yes I have a sample repo here
https://github.com/qngdt/serverless-python-package-warmup

**Comment by juanjoDiaz** [comment]
Hi @qngdt,

Your repo is missing the package.json, so there is no way for me to know which version of serverless or the plugins you are using.

Are you using the latest warmup plugin?
You might be seeing an issue that was introduced in v6.1.0 and fixed in v7.0.1

**Comment by qngdt** [comment]
> Hi @qngdt,
> 
> Your repo is missing the package.json, so there is no way for me to know which version of serverless or the plugins you are using.
> 
> Are you using the latest warmup plugin? You might be seeing an issue that was introduced in v6.1.0 and fixed in v7.0.1

Hi @juanjoDiaz,

I have updated the repo with the `package.json` files. Sorry I did not realize that the example repo from serverless doesn't contain those. The error is still persist though.

Thanks for still keep eye on this issue.

**Comment by juanjoDiaz** [comment]
Hi @qngdt,

The problem is here: https://github.com/ubaniabalogun/serverless-package-python-functions/blob/c8ce439fa46534716d0ebb9fa7e63298960474b0/index.js#L40-L46

The warmup plugin does a process to reset missconfigurations applied by plugins like [serverless-package-python-functions](https://github.com/ubaniabalogun/serverless-package-python-functions), webpack, bundle, etc.

Unfortunately, because the [serverless-package-python-functions](https://github.com/ubaniabalogun/serverless-package-python-functions) plugin doesn't override the config but modifies. The fix doesn't work here.

The plugin should not modify functions that are not even Python to start with. Adding a check for that would be trivial.

Another solution could be for the author of the plugin to update his code so it overrides the setting, doesn't update the actual object:
```js
  autoconfigArtifacts() {
    _.map(this.serverless.service.functions, (func_config, func_name) => {
      let autoArtifact = `${this.buildDir}/${func_config.name}.zip`
      func_config = {
        ...func_config,
        package: {
          ...func_config.package,
          artifact = func_config.package.artifact || autoArtifact,
        }
      }
    })
  }
```

So, unfortunately, you need to create an issue or a PR on that plugin. And it doesn't seem very well maintained 🙁
